apiVersion: v1
kind: Service
metadata:
  name: orderer{nodeNum}
  labels:
    run: orderer{nodeNum}
spec:
  type: ClusterIP
  selector:
    name: orderer{nodeNum}
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer{nodeNum}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orderer{nodeNum}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8443"
        prometheus.io/scrape: "true"
      labels:
        name: orderer{nodeNum}
    spec:
      volumes:
      - name: fabric-storage
        persistentVolumeClaim:
          claimName: azure-managed-disk-{nodeNum}
      - name: genesisblock
        secret:
           secretName: hlf-genesis-block
      - name: admincerts
        secret:
           secretName: hlf-admin-idcert
      - name: signcerts
        secret:
           secretName: hlforderer{nodeNum}-idcert
      - name: keystore
        secret:
           secretName: hlforderer{nodeNum}-idkey
      - name: cacerts
        secret:
           secretName: hlf-ca-idcert
      - name: tls-cacerts
        secret:
           secretName: hlf-tlsca-idcert
      - name: tls-keystore
        secret:
           secretName: hlforderer{nodeNum}-tls-idkey
      - name: tls-signcerts
        secret:
           secretName: hlforderer{nodeNum}-tls-idcert
      imagePullSecrets:
      - name: fabric-tools-secrets
      containers:
      - name: orderer
        image: hlfakstemplate.azurecr.io/hyperledger/fabric-orderer:1.4.4
        command: ["sh", "-c", "orderer"]
        env:
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: CONFIGTX_ORDERER_ADDRESSES
          value: "orderer{nodeNum}:7050"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        - name: FABRIC_LOGGING_SPEC
          value: "info"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: {orgName}
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/genesis.block
        - name: ORDERER_GENERAL_GENESISPROFILE
          value: initial
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /var/hyperledger/orderer/tls/ca.crt
        - name: ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED
          valueFrom:
            configMapKeyRef:
              name: mutual-tls
              key: enabled
        - name: ORDERER_GENERAL_TLS_CLIENTROOTCAS
          value: /var/hyperledger/orderer/tls/ca.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: /var/hyperledger/orderer/tls/ca.crt
        - name: GODEBUG
          value: "netdns=go"
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: :8443
        - name: ORDERER_METRICS_PROVIDER
          value: prometheus
        volumeMounts:
        - mountPath: /var/hyperledger/production/orderer/
          name: fabric-storage
          subPath: orderer{nodeNum}
        - mountPath: /var/hyperledger/orderer/genesis.block
          name: genesisblock
          subPath: genesis.block
          readOnly: true
        - mountPath: /var/hyperledger/orderer/msp/admincerts
          name: admincerts
          readOnly: true
        - mountPath: /var/hyperledger/orderer/msp/cacerts
          name: cacerts
          readOnly: true
        - mountPath: /var/hyperledger/orderer/msp/keystore
          name: keystore
          readOnly: true
        - mountPath: /var/hyperledger/orderer/msp/signcerts
          name: signcerts
          readOnly: true
        - mountPath: /var/hyperledger/orderer/tls/server.key
          name: tls-keystore
          subPath: server.key
          readOnly: true
        - mountPath: /var/hyperledger/orderer/tls/server.crt
          name: tls-signcerts
          subPath: server.crt
          readOnly: true
        - mountPath: /var/hyperledger/orderer/tls/ca.crt
          name: tls-cacerts
          subPath: ca.crt
          readOnly: true
        workingDir: /var/hyperledger/orderer 
